name: Build and Upload Artifact
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Create JAR file
        run: ./gradlew shadowJar
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: JAR Files
          path: build/libs/*.jar
